<?php
G::LoadClass("plugin");

if(!empty ($_POST['dd_val'])){
require_once ("DashboardReport/classes/class.dashletDashboardReport.php");
$call = new dashletDashboardReport();
$call->render($_POST['dd_val']);
}

class DashboardReportPlugin extends PMPlugin
{
  private $dashletsUids;
  
  public function DashboardReportPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "DashboardReport Plugin";
    $this->sDescription  = "Autogenerated plugin for class DashboardReport";
    $this->sPluginFolder = "DashboardReport";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    $this->dashletsUids = array(
      array("DAS_UID" => "87192059758942ac7e310b8038493152",
            "DAS_CLASS" => "dashletDashboardReport",
            "DAS_TITLE" => "Dashlet DashboardReport",
            "DAS_DESCRIPTION" => "Dashlet DashboardReport",
            "DAS_VERSION" => "1.0",
            "DAS_CREATE_DATE" => date("Y-m-d"),
            "DAS_UPDATE_DATE" => date("Y-m-d"))
    );
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerPmFunction();
    
    $this->registerDashlets();
  }

  public function install()
  {
  }
  
  public function enable()
  {
    $this->dashletInsert();
  }

  public function disable()
  {
    $this->dashletDelete();
  }
  
  public function dashletInsert()
  {
    require_once ("classes/model/Dashlet.php");
    
    $connection = Propel::getConnection(DashletPeer::DATABASE_NAME);
    
    foreach ($this->dashletsUids as $dashletData) {
      $dashlet = new Dashlet();
      
      if (is_null($dashlet->load($dashletData["DAS_UID"]))) {
        $dashlet->fromArray($dashletData, BasePeer::TYPE_FIELDNAME);
        $connection->begin();
        $dashlet->save();
        $connection->commit();
      }
    }
  }
  
  public function dashletDelete()
  {
    require_once ("classes/model/Dashlet.php");
    
    foreach ($this->dashletsUids as $dashletData) {
      $criteria = new Criteria("workflow");
      $criteria->add(DashletPeer::DAS_UID, $dashletData["DAS_UID"]);
      DashletPeer::doDelete($criteria);
    }
  }
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("DashboardReport", __FILE__);
